// frontend/constants/productAttributes.js

export const ATTRIBUTE_SUGGESTIONS = {
  Size: [
    { value: "Small", label: "Small (S)" },
    { value: "Medium", label: "Medium (M)" },
    { value: "Large", label: "Large (L)" },
    { value: "XL", label: "Extra Large (XL)" },
    { value: "XXL", label: "Double Extra Large (XXL)" },
    { value: "28", label: "28" },
    { value: "30", label: "30" },
    { value: "32", label: "32" },
    { value: "34", label: "34" },
    { value: "36", label: "36" },
  ],
  Color: [
    { value: "Red", label: "Red" },
    { value: "Blue", label: "Blue" },
    { value: "Green", label: "Green" },
    { value: "Black", label: "Black" },
    { value: "White", label: "White" },
    { value: "Yellow", label: "Yellow" },
    { value: "Purple", label: "Purple" },
    { value: "Orange", label: "Orange" },
    { value: "Grey", label: "Grey" },
    { value: "Navy", label: "Navy" },
  ],
  Material: [
    { value: "Cotton", label: "Cotton" },
    { value: "Polyester", label: "Polyester" },
    { value: "Wool", label: "Wool" },
    { value: "Silk", label: "Silk" },
    { value: "Leather", label: "Leather" },
    { value: "Denim", label: "Denim" },
    { value: "Linen", label: "Linen" },
    { value: "Plastic", label: "Plastic" },
    { value: "Metal", label: "Metal" },
    { value: "Wood", label: "Wood" },
  ],
  Weight: [
    { value: "100g", label: "100g" },
    { value: "250g", label: "250g" },
    { value: "500g", label: "500g" },
    { value: "1kg", label: "1kg" },
    { value: "2kg", label: "2kg" },
    { value: "5kg", label: "5kg" },
  ],
  Volume: [
    { value: "100ml", label: "100ml" },
    { value: "250ml", label: "250ml" },
    { value: "500ml", label: "500ml" },
    { value: "1L", label: "1L" },
    { value: "1.5L", label: "1.5L" },
    { value: "2L", label: "2L" },
    { value: "5L", label: "5L" },
  ],
};

export const COMMON_ATTRIBUTE_KEYS = [
  "Size",
  "Color",
  "Material",
  "Weight",
  "Volume",
  "Style",
  "Model",
  "Pack Size",
  "Dimensions",
];
